# Generated by Django 3.1.5 on 2021-01-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=60)),
                ('title', models.CharField(default=True, max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateField(blank=True)),
            ],
        ),
    ]
